import { useState } from 'react'

function ResultCard({ result, confidence }) {
  const isHate = result === 'hate'
  const pct    = Math.round(confidence)

  return (
    <div className={`relative rounded-2xl p-8 overflow-hidden border animate-fade-up
      shadow-[0_4px_24px_rgba(0,0,0,0.5)]
      ${isHate
        ? 'border-[#ff4d4d50] bg-gradient-to-br from-[#111111] to-[#ff4d4d08]'
        : 'border-[#39d35350] bg-gradient-to-br from-[#111111] to-[#39d35308]'
      }`}
    >
      {/* Top stripe */}
      <div className={`absolute top-0 left-0 right-0 h-[3px]
        ${isHate
          ? 'bg-gradient-to-r from-[#ff4d4d] to-[#ff8080]'
          : 'bg-gradient-to-r from-[#39d353] to-[#7cfc7c]'
        }`}
      />

      {/* Header row */}
      <div className="flex items-center justify-between flex-wrap gap-4 mb-6">

        {/* Verdict */}
        <div className="flex items-center gap-4">
          <span className="text-4xl leading-none">{isHate ? '❌' : '✅'}</span>
          <div>
            <span className="block text-[0.7rem] uppercase tracking-widest text-gray-500 font-semibold">
              Detection Result
            </span>
            <span className={`font-display text-2xl tracking-wide leading-tight
              ${isHate ? 'text-[#ff4d4d]' : 'text-[#39d353]'}`}
            >
              {isHate ? 'Hate Speech Detected' : 'Safe Text'}
            </span>
          </div>
        </div>

        {/* Confidence number */}
        <div className="flex flex-col items-end gap-1">
          <span className="text-[0.7rem] uppercase tracking-widest text-gray-500 font-semibold">
            Confidence
          </span>
          <span className="font-mono text-4xl font-bold text-gray-100 leading-none">
            {pct}<span className="text-xl text-gray-400">%</span>
          </span>
        </div>
      </div>

      {/* Progress bar */}
      <div>
        <div className="flex justify-between text-xs text-gray-500 font-medium mb-2">
          <span>Confidence Level</span>
          <span>{pct}%</span>
        </div>
        <div className="w-full h-2 bg-[#181818] rounded-full overflow-hidden border border-[#1f1f1f]">
          <div
            className={`h-full rounded-full bar-fill
              ${isHate
                ? 'bg-gradient-to-r from-[#ff4d4d] to-[#ff7070]'
                : 'bg-gradient-to-r from-[#39d353] to-[#5dfc8a]'
              }`}
            style={{ '--bar-width': `${pct}%` }}
          />
        </div>
      </div>

      {/* Disclaimer */}
      <div className="mt-5 flex items-start gap-2 bg-[#181818] border border-[#1f1f1f]
                      rounded-md px-4 py-3 text-xs text-gray-500">
        <span>ℹ️</span>
        <span>
          This result is generated by a machine learning model and may not be 100% accurate.
          Always use human judgment for moderation decisions.
        </span>
      </div>
    </div>
  )
}

export default function Detect() {
  const [text,    setText]    = useState('')
  const [loading, setLoading] = useState(false)
  const [result,  setResult]  = useState(null)
  const [error,   setError]   = useState('')

  const MAX_CHARS = 1000

  async function handleDetect() {
    const trimmed = text.trim()
    if (!trimmed) { setError('Please enter some text to analyze.'); return }

    setLoading(true)
    setResult(null)
    setError('')

    try {
      const response = await fetch('http://localhost:5000/predict', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({ text: trimmed }),
      })

      if (!response.ok) throw new Error(`Server error: ${response.status}`)

      const data = await response.json()
      setResult(data)
    } catch (err) {
      setError(
        err.name === 'TypeError'
          ? 'Could not connect to the Flask backend. Make sure it is running on http://localhost:5000'
          : err.message || 'An unexpected error occurred.'
      )
    } finally {
      setLoading(false)
    }
  }

  function handleClear() { setText(''); setResult(null); setError('') }

  function handleKeyDown(e) {
    if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') handleDetect()
  }

  return (
    <main className="flex-1 max-w-3xl mx-auto w-full px-6 py-16">

      {/* Header */}
      <header className="mb-10 animate-fade-up">
        <span className="flex items-center gap-2 text-xs font-semibold uppercase
                         tracking-[0.14em] text-[#ffd60a] mb-3
                         before:content-[''] before:block before:w-6 before:h-0.5 before:bg-[#ffd60a]">
          AI Analysis
        </span>
        <h1 className="font-display text-[clamp(2rem,5vw,3.25rem)] text-gray-100 mb-1">
          DETECT HATE SPEECH
        </h1>
        <p className="text-sm text-gray-500">
          Paste or type any text below and click Detect to analyze it instantly.
        </p>
      </header>

      {/* Input card */}
      <div className="animate-fade-up-1 bg-[#111111] border border-[#1f1f1f] rounded-2xl p-8 mb-6
                      shadow-[0_4px_24px_rgba(0,0,0,0.5)]
                      transition-all duration-300
                      focus-within:border-[#ffd60a50] focus-within:shadow-[0_4px_24px_rgba(0,0,0,0.5),0_0_0_1px_rgba(255,214,10,0.12)]">

        {/* Label row */}
        <div className="flex items-center justify-between text-xs font-semibold uppercase
                        tracking-widest text-gray-500 mb-3">
          <span>Input Text</span>
          <span className="font-mono">{text.length} / {MAX_CHARS}</span>
        </div>

        {/* Textarea */}
        <textarea
          className="w-full min-h-[180px] bg-[#181818] border border-[#1f1f1f] rounded-xl
                     text-gray-100 font-body text-base leading-relaxed
                     px-5 py-4 resize-y outline-none
                     placeholder:text-gray-600
                     transition-all duration-200
                     focus:border-[#ffd60a60] focus:bg-[#141414]"
          placeholder="Type or paste text here to check for hate speech..."
          value={text}
          onChange={(e) => { if (e.target.value.length <= MAX_CHARS) setText(e.target.value) }}
          onKeyDown={handleKeyDown}
          rows={7}
          spellCheck={false}
        />

        {/* Actions row */}
        <div className="flex items-center justify-between mt-5 gap-4 flex-wrap">
          <div className="flex gap-3 flex-wrap">
            {/* Detect button */}
            <button
              onClick={handleDetect}
              disabled={loading || !text.trim()}
              className="inline-flex items-center gap-2 px-8 py-3 rounded
                         bg-[#ffd60a] text-black font-bold text-base
                         transition-all duration-200
                         hover:bg-[#ffe033] hover:-translate-y-0.5
                         hover:shadow-[0_8px_32px_rgba(255,214,10,0.35)]
                         disabled:opacity-50 disabled:cursor-not-allowed
                         disabled:translate-y-0 disabled:shadow-none"
            >
              {loading ? (
                <>
                  <span className="w-4 h-4 rounded-full border-2 border-black/20
                                   border-t-black animate-spin-btn flex-shrink-0" />
                  Analyzing...
                </>
              ) : ' Detect'}
            </button>

            {/* Clear button */}
            <button
              onClick={handleClear}
              disabled={loading}
              className="px-5 py-3 rounded text-sm font-medium text-gray-500
                         border border-[#1f1f1f] transition-all duration-200
                         hover:text-gray-300 hover:border-[#2a2a2a]
                         disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Clear
            </button>
          </div>
          <span className="text-xs text-gray-600">Ctrl + Enter to run</span>
        </div>
      </div>

      {/* Error */}
      {error && (
        <div className="flex items-center gap-3 bg-[#ff4d4d10] border border-[#ff4d4d40]
                        rounded-xl px-6 py-4 text-sm text-[#ff4d4d] animate-fade-up mb-4">
          <span>⚠️</span>
          <span>{error}</span>
        </div>
      )}

      {/* Result */}
      {result && !error && (
        <ResultCard result={result.result} confidence={result.confidence} />
      )}
    </main>
  )
}